### ISSUE TITLE
ImportError: cannot import name 'Nyamuk' from 'nyamuk'

### ISSUE THREAD

**Issue by pahariwalla** [iwanbk/nyamuk#25]
Thank you for writing/maintaining this code.   I'm brand new (today) to Python.  Running in Windows 10 Pro, just downloaded Python 3.7.0.   Eventually, I will be running this on a Raspberry PI in a Docker container, but I want to learn a bit of Python first and see if I can communicate with a Mosquitto MQTT server.  

I have pip installed nyamuk: 
`Collecting nyamuk
  Downloading https://files.pythonhosted.org/packages/de/44/1a25ae956b13341cb2e3d54d1dc3d3cdd3a687f6e226f5f850848133767a/nyamuk-v0.2.0.tar.gz
Installing collected packages: nyamuk
  Running setup.py install for nyamuk ... done
Successfully installed nyamuk-0.2.0`

When I run the Publish sample  it throws 
`ImportError: cannot import name 'Nyamuk' from 'nyamuk' (C:\Users\Rajinder\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nyamuk\__init__.py)`

I'm hoping you can help me out.  Thanks very much

**Comment by gbour** [comment]
Hello @pahariwalla 

nyamuk is not working with python > 2.7 right now (this is planned).
So I guess your problem starts from there (try to downgrade your python version).

**Comment by gbour** [comment]
py3 support will be implemented soon
